version: "3.9"
services:
  db:
    image: mariadb:10.3.32
    command: --default-authentication-plugin=mysql_native_password
    hostname: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blades
      MYSQL_USER: backend
      MYSQL_PASSWORD: password


  frontend:
    image: nginx
    hostname: frontend
    ports:
      - "80:80"
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        GATSBY_DOMAIN: "http://blades.ericmarcantonio.com"
        GATSBY_PORT: 3000

  backend:
    image: golang:1.17
    hostname: backend
    ports:
      - "3000:3000"
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        user: backend
        db: blades
        pass: password
        port: 3306
        domain: db